version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-crud-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-kx70xen8l6tk"
s3_prefix = "sam-crud-api"
region = "eu-west-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
